// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruequeU.DAO;

#nullable disable

namespace TruequeU.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518002450_RemoveSeedData")]
    partial class RemoveSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0defdb54-17a0-43cc-929b-5d2402cc11c5",
                            Email = "juan@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JUAN@TEST.COM",
                            NormalizedUserName = "JUAN@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAE...",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "45123331-52d8-4153-9292-c27199c407b3",
                            TwoFactorEnabled = false,
                            UserName = "juan@test.com"
                        },
                        new
                        {
                            Id = "user2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "403e1e8c-9b94-41b3-bc02-34a1eea81175",
                            Email = "ana@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANA@TEST.COM",
                            NormalizedUserName = "ANA@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAE...",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "056cb731-c640-4a64-ba46-a72ac564080b",
                            TwoFactorEnabled = false,
                            UserName = "ana@test.com"
                        },
                        new
                        {
                            Id = "user3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a195dfd4-e0a3-475c-a922-49910c69d2ea",
                            Email = "carlos@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CARLOS@TEST.COM",
                            NormalizedUserName = "CARLOS@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAE...",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3b6a5d4b-9b5c-4a6a-a97b-1ab5b63119be",
                            TwoFactorEnabled = false,
                            UserName = "carlos@test.com"
                        },
                        new
                        {
                            Id = "user4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1ec2ff90-8269-426c-b3cb-b74ba65c3dc5",
                            Email = "laura@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LAURA@TEST.COM",
                            NormalizedUserName = "LAURA@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAE...",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f0afa0e1-18fe-4e24-97df-bb340736803d",
                            TwoFactorEnabled = false,
                            UserName = "laura@test.com"
                        },
                        new
                        {
                            Id = "user5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0286d656-c5ab-46a7-a1cb-1f90550afa7e",
                            Email = "pedro@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PEDRO@TEST.COM",
                            NormalizedUserName = "PEDRO@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAE...",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0268e7cb-f2c7-416c-b8d4-be05f76dc9e9",
                            TwoFactorEnabled = false,
                            UserName = "pedro@test.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TruequeU.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ListingId");

                    b.HasIndex("SellerId");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc01"),
                            BuyerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02"),
                            SellerId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc02"),
                            BuyerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa03"),
                            SellerId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc03"),
                            BuyerId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa04"),
                            SellerId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc04"),
                            BuyerId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa05"),
                            SellerId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc05"),
                            BuyerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa06"),
                            SellerId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc06"),
                            BuyerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa07"),
                            SellerId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc07"),
                            BuyerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa08"),
                            SellerId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc08"),
                            BuyerId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa09"),
                            SellerId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc09"),
                            BuyerId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa10"),
                            SellerId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc10"),
                            BuyerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa11"),
                            SellerId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc11"),
                            BuyerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa12"),
                            SellerId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc12"),
                            BuyerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa13"),
                            SellerId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc13"),
                            BuyerId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa14"),
                            SellerId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc14"),
                            BuyerId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa15"),
                            SellerId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc15"),
                            BuyerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa01"),
                            SellerId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc16"),
                            BuyerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02"),
                            SellerId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc17"),
                            BuyerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa03"),
                            SellerId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc18"),
                            BuyerId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa04"),
                            SellerId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc19"),
                            BuyerId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa05"),
                            SellerId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc20"),
                            BuyerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa06"),
                            SellerId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("TruequeU.Models.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("TruequeU.Models.Images", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("listing_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("listing_id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb01"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02"),
                            url = "https://placeholder.com/img1.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb02"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa03"),
                            url = "https://placeholder.com/img2.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb03"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa04"),
                            url = "https://placeholder.com/img3.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb04"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa05"),
                            url = "https://placeholder.com/img4.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb05"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa06"),
                            url = "https://placeholder.com/img5.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb06"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa07"),
                            url = "https://placeholder.com/img6.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb07"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa08"),
                            url = "https://placeholder.com/img7.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb08"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa09"),
                            url = "https://placeholder.com/img8.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb09"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa10"),
                            url = "https://placeholder.com/img9.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb10"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa11"),
                            url = "https://placeholder.com/img10.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb11"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa12"),
                            url = "https://placeholder.com/img11.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb12"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa13"),
                            url = "https://placeholder.com/img12.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb13"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa14"),
                            url = "https://placeholder.com/img13.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb14"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa15"),
                            url = "https://placeholder.com/img14.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb15"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa01"),
                            url = "https://placeholder.com/img15.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb16"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02"),
                            url = "https://placeholder.com/img16.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb17"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa03"),
                            url = "https://placeholder.com/img17.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb18"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa04"),
                            url = "https://placeholder.com/img18.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb19"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa05"),
                            url = "https://placeholder.com/img19.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb20"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa06"),
                            url = "https://placeholder.com/img20.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb21"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa07"),
                            url = "https://placeholder.com/img21.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb22"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa08"),
                            url = "https://placeholder.com/img22.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb23"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa09"),
                            url = "https://placeholder.com/img23.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb24"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa10"),
                            url = "https://placeholder.com/img24.jpg"
                        },
                        new
                        {
                            id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb25"),
                            listing_id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa11"),
                            url = "https://placeholder.com/img25.jpg"
                        });
                });

            modelBuilder.Entity("TruequeU.Models.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa01"),
                            Category = "Electrónica",
                            Condition = "Usado",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descripción del producto 1",
                            IsHidden = false,
                            Location = "Universidad",
                            Price = 11000m,
                            State = "Disponible",
                            Title = "Producto 1",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02"),
                            Category = "Electrónica",
                            Condition = "Usado",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descripción del producto 2",
                            IsHidden = false,
                            Location = "Universidad",
                            Price = 12000m,
                            State = "Disponible",
                            Title = "Producto 2",
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa03"),
                            Category = "Electrónica",
                            Condition = "Usado",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descripción del producto 3",
                            IsHidden = false,
                            Location = "Universidad",
                            Price = 13000m,
                            State = "Disponible",
                            Title = "Producto 3",
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa04"),
                            Category = "Electrónica",
                            Condition = "Usado",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descripción del producto 4",
                            IsHidden = false,
                            Location = "Universidad",
                            Price = 14000m,
                            State = "Disponible",
                            Title = "Producto 4",
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa05"),
                            Category = "Electrónica",
                            Condition = "Usado",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descripción del producto 5",
                            IsHidden = false,
                            Location = "Universidad",
                            Price = 15000m,
                            State = "Disponible",
                            Title = "Producto 5",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa06"),
                            Category = "Electrónica",
                            Condition = "Usado",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descripción del producto 6",
                            IsHidden = false,
                            Location = "Universidad",
                            Price = 16000m,
                            State = "Disponible",
                            Title = "Producto 6",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa07"),
                            Category = "Electrónica",
                            Condition = "Usado",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descripción del producto 7",
                            IsHidden = false,
                            Location = "Universidad",
                            Price = 17000m,
                            State = "Disponible",
                            Title = "Producto 7",
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa08"),
                            Category = "Electrónica",
                            Condition = "Usado",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descripción del producto 8",
                            IsHidden = false,
                            Location = "Universidad",
                            Price = 18000m,
                            State = "Disponible",
                            Title = "Producto 8",
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa09"),
                            Category = "Electrónica",
                            Condition = "Usado",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descripción del producto 9",
                            IsHidden = false,
                            Location = "Universidad",
                            Price = 19000m,
                            State = "Disponible",
                            Title = "Producto 9",
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa10"),
                            Category = "Electrónica",
                            Condition = "Usado",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descripción del producto 10",
                            IsHidden = false,
                            Location = "Universidad",
                            Price = 20000m,
                            State = "Disponible",
                            Title = "Producto 10",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa11"),
                            Category = "Electrónica",
                            Condition = "Usado",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descripción del producto 11",
                            IsHidden = false,
                            Location = "Universidad",
                            Price = 21000m,
                            State = "Disponible",
                            Title = "Producto 11",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa12"),
                            Category = "Electrónica",
                            Condition = "Usado",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descripción del producto 12",
                            IsHidden = false,
                            Location = "Universidad",
                            Price = 22000m,
                            State = "Disponible",
                            Title = "Producto 12",
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa13"),
                            Category = "Electrónica",
                            Condition = "Usado",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descripción del producto 13",
                            IsHidden = false,
                            Location = "Universidad",
                            Price = 23000m,
                            State = "Disponible",
                            Title = "Producto 13",
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa14"),
                            Category = "Electrónica",
                            Condition = "Usado",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descripción del producto 14",
                            IsHidden = false,
                            Location = "Universidad",
                            Price = 24000m,
                            State = "Disponible",
                            Title = "Producto 14",
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa15"),
                            Category = "Electrónica",
                            Condition = "Usado",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descripción del producto 15",
                            IsHidden = false,
                            Location = "Universidad",
                            Price = 25000m,
                            State = "Disponible",
                            Title = "Producto 15",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("TruequeU.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd01"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc02"),
                            Content = "Mensaje 1",
                            SenderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SentAt = new DateTime(2024, 1, 1, 0, 1, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd02"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc03"),
                            Content = "Mensaje 2",
                            SenderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SentAt = new DateTime(2024, 1, 1, 0, 2, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd03"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc04"),
                            Content = "Mensaje 3",
                            SenderId = new Guid("44444444-4444-4444-4444-444444444444"),
                            SentAt = new DateTime(2024, 1, 1, 0, 3, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd04"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc05"),
                            Content = "Mensaje 4",
                            SenderId = new Guid("55555555-5555-5555-5555-555555555555"),
                            SentAt = new DateTime(2024, 1, 1, 0, 4, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd05"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc06"),
                            Content = "Mensaje 5",
                            SenderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SentAt = new DateTime(2024, 1, 1, 0, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd06"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc07"),
                            Content = "Mensaje 6",
                            SenderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SentAt = new DateTime(2024, 1, 1, 0, 6, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd07"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc08"),
                            Content = "Mensaje 7",
                            SenderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SentAt = new DateTime(2024, 1, 1, 0, 7, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd08"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc09"),
                            Content = "Mensaje 8",
                            SenderId = new Guid("44444444-4444-4444-4444-444444444444"),
                            SentAt = new DateTime(2024, 1, 1, 0, 8, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd09"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc10"),
                            Content = "Mensaje 9",
                            SenderId = new Guid("55555555-5555-5555-5555-555555555555"),
                            SentAt = new DateTime(2024, 1, 1, 0, 9, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd10"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc11"),
                            Content = "Mensaje 10",
                            SenderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SentAt = new DateTime(2024, 1, 1, 0, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd11"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc12"),
                            Content = "Mensaje 11",
                            SenderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SentAt = new DateTime(2024, 1, 1, 0, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd12"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc13"),
                            Content = "Mensaje 12",
                            SenderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SentAt = new DateTime(2024, 1, 1, 0, 12, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd13"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc14"),
                            Content = "Mensaje 13",
                            SenderId = new Guid("44444444-4444-4444-4444-444444444444"),
                            SentAt = new DateTime(2024, 1, 1, 0, 13, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd14"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc15"),
                            Content = "Mensaje 14",
                            SenderId = new Guid("55555555-5555-5555-5555-555555555555"),
                            SentAt = new DateTime(2024, 1, 1, 0, 14, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd15"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc16"),
                            Content = "Mensaje 15",
                            SenderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SentAt = new DateTime(2024, 1, 1, 0, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd16"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc17"),
                            Content = "Mensaje 16",
                            SenderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SentAt = new DateTime(2024, 1, 1, 0, 16, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd17"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc18"),
                            Content = "Mensaje 17",
                            SenderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SentAt = new DateTime(2024, 1, 1, 0, 17, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd18"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc19"),
                            Content = "Mensaje 18",
                            SenderId = new Guid("44444444-4444-4444-4444-444444444444"),
                            SentAt = new DateTime(2024, 1, 1, 0, 18, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd19"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc20"),
                            Content = "Mensaje 19",
                            SenderId = new Guid("55555555-5555-5555-5555-555555555555"),
                            SentAt = new DateTime(2024, 1, 1, 0, 19, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd20"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc01"),
                            Content = "Mensaje 20",
                            SenderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SentAt = new DateTime(2024, 1, 1, 0, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd21"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc02"),
                            Content = "Mensaje 21",
                            SenderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SentAt = new DateTime(2024, 1, 1, 0, 21, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd22"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc03"),
                            Content = "Mensaje 22",
                            SenderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SentAt = new DateTime(2024, 1, 1, 0, 22, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd23"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc04"),
                            Content = "Mensaje 23",
                            SenderId = new Guid("44444444-4444-4444-4444-444444444444"),
                            SentAt = new DateTime(2024, 1, 1, 0, 23, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd24"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc05"),
                            Content = "Mensaje 24",
                            SenderId = new Guid("55555555-5555-5555-5555-555555555555"),
                            SentAt = new DateTime(2024, 1, 1, 0, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd25"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc06"),
                            Content = "Mensaje 25",
                            SenderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SentAt = new DateTime(2024, 1, 1, 0, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd26"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc07"),
                            Content = "Mensaje 26",
                            SenderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SentAt = new DateTime(2024, 1, 1, 0, 26, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd27"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc08"),
                            Content = "Mensaje 27",
                            SenderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SentAt = new DateTime(2024, 1, 1, 0, 27, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd28"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc09"),
                            Content = "Mensaje 28",
                            SenderId = new Guid("44444444-4444-4444-4444-444444444444"),
                            SentAt = new DateTime(2024, 1, 1, 0, 28, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd29"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc10"),
                            Content = "Mensaje 29",
                            SenderId = new Guid("55555555-5555-5555-5555-555555555555"),
                            SentAt = new DateTime(2024, 1, 1, 0, 29, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd30"),
                            ChatId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc11"),
                            Content = "Mensaje 30",
                            SenderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SentAt = new DateTime(2024, 1, 1, 0, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TruequeU.Models.ModerationAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ListingId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("ModerationActions");
                });

            modelBuilder.Entity("TruequeU.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReportedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee01"),
                            Comment = "Reporte 1",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02"),
                            Reason = "Contenido inapropiado",
                            ReportedUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ReporterId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Pendiente"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee02"),
                            Comment = "Reporte 2",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa03"),
                            Reason = "Contenido inapropiado",
                            ReportedUserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ReporterId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Pendiente"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee03"),
                            Comment = "Reporte 3",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa04"),
                            Reason = "Contenido inapropiado",
                            ReportedUserId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ReporterId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Status = "Pendiente"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee04"),
                            Comment = "Reporte 4",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa05"),
                            Reason = "Contenido inapropiado",
                            ReportedUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ReporterId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Status = "Pendiente"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee05"),
                            Comment = "Reporte 5",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa06"),
                            Reason = "Contenido inapropiado",
                            ReportedUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ReporterId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Pendiente"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee06"),
                            Comment = "Reporte 6",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa07"),
                            Reason = "Contenido inapropiado",
                            ReportedUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ReporterId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Pendiente"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee07"),
                            Comment = "Reporte 7",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa08"),
                            Reason = "Contenido inapropiado",
                            ReportedUserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ReporterId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Pendiente"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee08"),
                            Comment = "Reporte 8",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa09"),
                            Reason = "Contenido inapropiado",
                            ReportedUserId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ReporterId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Status = "Pendiente"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee09"),
                            Comment = "Reporte 9",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa10"),
                            Reason = "Contenido inapropiado",
                            ReportedUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ReporterId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Status = "Pendiente"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee10"),
                            Comment = "Reporte 10",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa11"),
                            Reason = "Contenido inapropiado",
                            ReportedUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ReporterId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Pendiente"
                        });
                });

            modelBuilder.Entity("TruequeU.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IdentityUserId = "user1",
                            IsSuspended = false,
                            Name = "Juan",
                            Program = "Sistemas",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            IdentityUserId = "user2",
                            IsSuspended = false,
                            Name = "Ana",
                            Program = "Industrial",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            IdentityUserId = "user3",
                            IsSuspended = false,
                            Name = "Carlos",
                            Program = "Civil",
                            Rating = 3.7999999999999998
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            IdentityUserId = "user4",
                            IsSuspended = false,
                            Name = "Laura",
                            Program = "Electrónica",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            IdentityUserId = "user5",
                            IsSuspended = false,
                            Name = "Pedro",
                            Program = "Mecánica",
                            Rating = 3.5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TruequeU.Models.Chat", b =>
                {
                    b.HasOne("TruequeU.Models.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TruequeU.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruequeU.Models.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Listing");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("TruequeU.Models.Favorite", b =>
                {
                    b.HasOne("TruequeU.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TruequeU.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruequeU.Models.Images", b =>
                {
                    b.HasOne("TruequeU.Models.Listing", "ListingAsc")
                        .WithMany("Images")
                        .HasForeignKey("listing_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListingAsc");
                });

            modelBuilder.Entity("TruequeU.Models.Listing", b =>
                {
                    b.HasOne("TruequeU.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruequeU.Models.Message", b =>
                {
                    b.HasOne("TruequeU.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruequeU.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("TruequeU.Models.ModerationAction", b =>
                {
                    b.HasOne("TruequeU.Models.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruequeU.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId");

                    b.HasOne("TruequeU.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId");

                    b.Navigation("Admin");

                    b.Navigation("Listing");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("TruequeU.Models.Report", b =>
                {
                    b.HasOne("TruequeU.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId");

                    b.HasOne("TruequeU.Models.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId");

                    b.HasOne("TruequeU.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("TruequeU.Models.User", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("TruequeU.Models.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TruequeU.Models.Listing", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("TruequeU.Models.User", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
